config/routes.rb
DmsExt::Application.routes.draw do

  resources :opts

  match 'manage' => 'manage#index'
  
  resources :clients
  resources :interiors
  resources :colors

  devise_for :users

  resource :trade_ins

  resources :calendar do
    member do
      get 'day'
    end
  end

  resources :upload do
    member do
      get 'state'
      post 'state'
    end
  end

  resources :people do
    resources :communications
  end

  resources :cars do
    resource :contract
    resource :act
    resource :dkp
    resource :ckp
    resource :proposal
  end

  resources :models
  resources :managers

  resources :communications do
    member do
      get 'short'
    end
  end

  resources :contracts, :belongs_to => :car
  resources :proposals
  resources :checkins
  resources :acts
  resources :dkps

  root :to => 'cars#index'

  match 'cars/:id/info' => 'cars#info'
  match 'makedoc' => 'contracts#index'

end

app/models/opt.rb
class Opt < ActiveRecord::Base
  belongs_to :klasse

  def self.remove_duplicates
    Opt.find_each do |opt|
      opts = Opt.where(code: opt.code, klasse_id: opt.klasse_id)
      if opts.count > 1
        opts.where('id <> ?', opt.id).destroy_all
      end
    end
  end

  def self.organize
    Opt.find_each do |opt|
      opts = Opt.where(code: opt.code, desc: opt.desc)
      next unless opts.count > 1
      opts.where('id <> ?', opt.id).delete_all
      opt.update_attributes klasse_id: nil
    end
  end
end

app/controllers/opts_controller.rb
class OptsController < ApplicationController
  # GET /opts
  # GET /opts.json
  layout 'manage'
  def index
    @opts = Opt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @opts }
    end
  end

  # GET /opts/1
  # GET /opts/1.json
  def show
    @opt = Opt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opt }
    end
  end

  # GET /opts/new
  # GET /opts/new.json
  def new
    @opt = Opt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opt }
    end
  end

  # GET /opts/1/edit
  def edit
    @opt = Opt.find(params[:id])
  end

  # POST /opts
  # POST /opts.json
  def create
    @opt = Opt.new(params[:opt])

    respond_to do |format|
      if @opt.save
        format.html { redirect_to @opt, notice: 'Opt was successfully created.' }
        format.json { render json: @opt, status: :created, location: @opt }
      else
        format.html { render action: "new" }
        format.json { render json: @opt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opts/1
  # PUT /opts/1.json
  def update
    @opt = Opt.find(params[:id])

    respond_to do |format|
      if @opt.update_attributes(params[:opt])
        format.html { redirect_to @opt, notice: 'Opt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opts/1
  # DELETE /opts/1.json
  def destroy
    @opt = Opt.find(params[:id])
    @opt.destroy

    respond_to do |format|
      format.html { redirect_to opts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/opts_helper.rb
module OptsHelper
end

app/views/opts/_form.html.haml
= form_for(@opt) do |f|
  - if @opt.errors.any?
    #error_explanation
      %h2
        = pluralize(@opt.errors.count, "error")
        prohibited this opt from being saved:
      %ul
        - @opt.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :code
    %br/
    = f.text_field :code
  .field
    = f.label :desc
    %br/
    = f.text_field :desc
  .field
    = f.label :pseudo_klasse
    %br/
    = f.text_field :pseudo_klasse
  .field
    = f.label :klasse_id
    %br/
    = f.number_field :klasse_id
  .actions
    = f.submit

app/views/opts/edit.html.haml
%h1 Editing opt
= render 'form'
= link_to 'Show', @opt
|
\#{link_to 'Back', opts_path}

app/views/opts/index.html.haml
%h1 Listing opts
%table.table.table-condensed.table-striped
  %tr
    %th Klasse
    %th Code
    %th Desc
    %th Pseudo klasse
    %th
    %th
    %th
  - @opts.each do |opt|
    %tr
      %td= opt.klasse.name
      %td= opt.code
      %td= opt.desc
      %td= opt.pseudo_klasse
      %td= link_to 'Show', opt
      %td= link_to 'Edit', edit_opt_path(opt)
      %td= link_to 'Destroy', opt, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Opt', new_opt_path

app/views/opts/new.html.haml
%h1 New opt
= render 'form'
= link_to 'Back', opts_path

app/views/opts/show.html.haml
%p#notice= notice
%p
  %b Code:
  = @opt.code
%p
  %b Desc:
  = @opt.desc
%p
  %b Pseudo klasse:
  = @opt.pseudo_klasse
%p
  %b Klasse:
  = @opt.klasse_id
= link_to 'Edit', edit_opt_path(@opt)
|
\#{link_to 'Back', opts_path}