config/routes.rb
DmsExt::Application.routes.draw do

  resources :opts

  match 'manage' => 'manage#index'
  
  resources :clients
  resources :interiors
  resources :colors

  devise_for :users

  resource :trade_ins

  resources :calendar do
    member do
      get 'day'
    end
  end

  resources :upload do
    member do
      get 'state'
      post 'state'
    end
  end

  resources :people do
    resources :communications
  end

  resources :cars do
    resource :contract
    resource :act
    resource :dkp
    resource :ckp
    resource :proposal
  end

  resources :models
  resources :managers

  resources :communications do
    member do
      get 'short'
    end
  end

  resources :contracts, :belongs_to => :car
  resources :proposals
  resources :checkins
  resources :acts
  resources :dkps

  root :to => 'cars#index'

  match 'cars/:id/info' => 'cars#info'
  match 'makedoc' => 'contracts#index'

end

app/models/interior.rb
class Interior < ActiveRecord::Base
  belongs_to :klasse
end

app/controllers/interiors_controller.rb
class InteriorsController < ApplicationController
  # GET /interiors
  # GET /interiors.json
  layout 'manage'
  
  def index
    @interiors = Interior.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interiors }
    end
  end

  # GET /interiors/1
  # GET /interiors/1.json
  def show
    @interior = Interior.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interior }
    end
  end

  # GET /interiors/new
  # GET /interiors/new.json
  def new
    @interior = Interior.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interior }
    end
  end

  # GET /interiors/1/edit
  def edit
    @interior = Interior.find(params[:id])
  end

  # POST /interiors
  # POST /interiors.json
  def create
    @interior = Interior.new(params[:interior])

    respond_to do |format|
      if @interior.save
        format.html { redirect_to @interior, notice: 'Interior was successfully created.' }
        format.json { render json: @interior, status: :created, location: @interior }
      else
        format.html { render action: "new" }
        format.json { render json: @interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interiors/1
  # PUT /interiors/1.json
  def update
    @interior = Interior.find(params[:id])

    respond_to do |format|
      if @interior.update_attributes(params[:interior])
        format.html { redirect_to @interior, notice: 'Interior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interiors/1
  # DELETE /interiors/1.json
  def destroy
    @interior = Interior.find(params[:id])
    @interior.destroy

    respond_to do |format|
      format.html { redirect_to interiors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interiors_helper.rb
module InteriorsHelper
end

app/views/interiors/_form.html.haml
= form_for(@interior) do |f|
  - if @interior.errors.any?
    #error_explanation
      %h2
        = pluralize(@interior.errors.count, "error")
        prohibited this interior from being saved:
      %ul
        - @interior.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :desc
    %br/
    = f.text_field :desc
  .field
    = f.label :code
    %br/
    = f.text_field :code
  .field
    = f.label :klasse_id
    %br/
    = f.number_field :klasse_id
  .actions
    = f.submit

app/views/interiors/edit.html.haml
%h1 Editing interior
= render 'form'
= link_to 'Show', @interior
|
\#{link_to 'Back', interiors_path}

app/views/interiors/index.html.haml
%h1 Интерьеры
= link_to 'New Interior', new_interior_path, :class => 'btn'

%table.table.table-condensed
  %tr
    %th Klasse
    %th Code
    %th Desc
    %th
    %th
    %th
  - @interiors.each do |interior|
    %tr
      %td= interior.klasse.name
      %td= interior.code
      %td= interior.desc
      %td
        %a.btn.btn-small{:href => edit_interior_path(interior)}
          %i.icon-edit
        
        
        
        %a.btn.btn-small.btn-error{:href => interior_path(interior), :method => :delete, data: { confirm: 'Are you sure?' }}
          %i.icon-trash
%br/
= link_to 'New Interior', new_interior_path, :class => 'btn'

app/views/interiors/new.html.haml
%h1 New interior
= render 'form'
= link_to 'Back', interiors_path

app/views/interiors/show.html.haml
%p#notice= notice
%p
  %b Desc:
  = @interior.desc
%p
  %b Code:
  = @interior.code
%p
  %b Klasse:
  = @interior.klasse_id
= link_to 'Edit', edit_interior_path(@interior)
|
\#{link_to 'Back', interiors_path}