config/routes.rb
DmsExt::Application.routes.draw do

  resources :opts

  match 'manage' => 'manage#index'
  
  resources :clients
  resources :interiors
  resources :colors

  devise_for :users

  resource :trade_ins

  resources :calendar do
    member do
      get 'day'
    end
  end

  resources :upload do
    member do
      get 'state'
      post 'state'
    end
  end

  resources :people do
    resources :communications
  end

  resources :cars do
    resource :contract
    resource :act
    resource :dkp
    resource :ckp
    resource :proposal
  end

  resources :models
  resources :managers

  resources :communications do
    member do
      get 'short'
    end
  end

  resources :contracts, :belongs_to => :car
  resources :proposals
  resources :checkins
  resources :acts
  resources :dkps

  root :to => 'cars#index'

  match 'cars/:id/info' => 'cars#info'
  match 'makedoc' => 'contracts#index'

end

app/models/client.rb
#encoding: utf-8
class Client < ActiveRecord::Base
  alias_attribute :contract_date, :date_contract
  # alias_attribute :birthday, :clientbirthday
  alias_attribute :id_series, :pas1
  alias_attribute :id_number, :pas2
  alias_attribute :id_dep, :pas3


  with_options :if => "cause == 1" do |client|
    client.validates :prepay, :cost, :clientbirthday, :phone1, :contract_date, :vin, :client_adress, :presence => 'true'
    client.validates_presence_of :id_series, :id_number, :id_dep
    client.validates_format_of :id_series, :id_number, :with => /[\d\s]+/
    client.validates_presence_of :fio
    # client.validates :car, :presence => true
  end

  with_options :if => 'cause == 5' do |client|
    client.validates_presence_of :fio, :manager, :trade_in_price, :trade_in_desc
    client.validates_associated :used_car
  end

  set_table_name '1_clients'

  has_one :used_car, :class_name => Car, :foreign_key => :used_vin, :primary_key => :used_vin
  has_one :car, :foreign_key => :order, :primary_key => :vin

  def price_kop
    if cost.to_s.split('.').size == 2
      kopejki = price.to_s.split('.')[1]
      propis = RuPropisju.kopeek(kopejki.to_i)
      if kopejki.to_i < 10
        propis = '0' + propis
      end

    else
      propis = '00 копеек'
    end
    if propis.to_i == 0
      propis = '00 копеек'
    end
    propis
  end

  def prepare_client_for_mssql
    new_client = Mssql.new
    new_client.firstname = fio.split(/\s/)[1]
    new_client.lastname = fio.split(/\s/)[0]
    new_client.dadname = fio.split(/\s/)[2]
    new_client.pass_num = pas1.gsub(/\s/, '').to_i
    new_client.pass_ser = pas2.gsub(/\s/, '').to_i
    new_client.pass_whom = pas3
    new_client.pass_when = pas4.strftime('%Y / %m / %d') if pas4
    new_client.address = client_adress
    new_client.birth = clientbirthday.strftime('%Y / %m / %d') if clientbirthday
    new_client.ordernum = vin
    new_client.price = cost
    new_client.prepaid = prepay
    new_client.dog_num = dg.year.to_s[2..3] + '/' + car.order.to_s[7..10] if car
    new_client.dog_date = dg.strftime('%Y / %m / %d')
    new_client.client_id = id    
    new_client
  end

  def exist_in_mssql?
    prepare_client_for_mssql.exist?
  end

  def write_to_ms_sql
    if id = prepare_client_for_mssql.exist?
      mssql = prepare_client_for_mssql
      mssql.updated = 1
      mssql.update(id)
    else
      mssql = prepare_client_for_mssql
      mssql.updated = 0
      mssql.save      
    end
  end

  def prepay_kop
    if cost.to_s.split('.').size == 2
      kopejki = prepay.to_s.split('.')[1]
      propis = RuPropisju.kopeek(kopejki.to_i)
      if kopejki.to_i < 10
        propis = '0' + propis
      end

    else
      propis = '00 копеек'
    end
    if propis.to_i == 0
      propis = '00 копеек'
    end
    propis
  end

  def short_name
    n = fio.split(/(\s|\.)/).delete_if { |i| i == '.' || i == ' ' }

    if n.count == 3
      "#{n[0]} #{n[1][0]}. #{n[2][0]}."
    else
      self.fio
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  layout 'manage'
  def index
    @clients = Client.where("vin <> ''").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for(@client) do |f|
  - if @client.errors.any?
    #error_explanation
      %h2
        = pluralize(@client.errors.count, "error")
        prohibited this client from being saved:
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :fio
    %br/
    = f.text_field :fio

  .field
    = f.label :phone1
    %br/
    = f.text_field :phone1
  .field
    = f.label :phone2
    %br/
    = f.text_field :phone2
  .field
    = f.label :phone3
    %br/
    = f.text_field :phone3
  .field
    = f.label :phone4
    %br/
    = f.text_field :phone4
  .field
    = f.label :date
    %br/
    = f.date_select :date
  .field
    = f.label :adress
    %br/
    = f.text_field :adress

  .field
    = f.label :brand
    %br/
    = f.text_field :brand
  .field
    = f.label :manager
    %br/
    = f.text_field :manager
  .field
    = f.label :model
    %br/
    = f.text_field :model
  .field
    = f.label :icon
    %br/
    = f.number_field :icon
  .field
    = f.label :out
    %br/
    = f.datetime_select :out
  .field
    = f.label :icon2
    %br/
    = f.number_field :icon2
  .field
    = f.label :vin
    %br/
    = f.text_field :vin
  .field
    = f.label :cost
    %br/
    = f.number_field :cost
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .field
    = f.label :commercial
    %br/
    = f.text_field :commercial
  .field
    = f.label :tmp
    %br/
    = f.text_field :tmp
  .field
    = f.label :files
    %br/
    = f.number_field :files
  .field
    = f.label :phone11
    %br/
    = f.text_field :phone11
  .field
    = f.label :phone22
    %br/
    = f.text_field :phone22
  .field
    = f.label :phone33
    %br/
    = f.text_field :phone33
  .field
    = f.label :phone44
    %br/
    = f.text_field :phone44
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :pas1
    %br/
    = f.text_field :pas1
  .field
    = f.label :pas2
    %br/
    = f.text_field :pas2
  .field
    = f.label :pas3
    %br/
    = f.text_field :pas3
  .field
    = f.label :clientbirthday
    %br/
    = f.date_select :clientbirthday
  .field
    = f.label :prepay
    %br/
    = f.text_field :prepay
  .field
    = f.label :date_contract
    %br/
    = f.date_select :date_contract
  .field
    = f.label :carpets
    %br/
    = f.check_box :carpets
  .field
    = f.label :mudguard
    %br/
    = f.check_box :mudguard
  .field
    = f.label :tech_1
    %br/
    = f.check_box :tech_1
  .field
    = f.label :tech_2
    %br/
    = f.check_box :tech_2
  .field
    = f.label :tires
    %br/
    = f.check_box :tires
  .field
    = f.label :pas4
    %br/
    = f.date_select :pas4
  .field
    = f.label :client_adress
    %br/
    = f.text_field :client_adress
  .field
    = f.label :cause
    %br/
    = f.number_field :cause
  .field
    = f.label :trade_in_price
    %br/
    = f.number_field :trade_in_price
  .field
    = f.label :trade_in_desc
    %br/
    = f.text_area :trade_in_desc
  .field
    = f.label :used_vin
    %br/
    = f.text_field :used_vin
  .actions
    = f.submit

app/views/clients/edit.html.haml
%h1 Editing client
= render 'form'
= link_to 'Show', @client
|
\#{link_to 'Back', clients_path}

app/views/clients/index.html.haml
%h1 Listing clients
= will_paginate @posts
%table.table-condenced.table.table-striped
  %tr
    %th
    %th Fio
    %th Comment
    %th Phone1
    / %th Phone2
    / %th Phone3
    / %th Phone4
    %th Date
    %th Adress
    
    %th Brand
    %th Manager
    %th Model
    / %th Icon
    / %th Creditmanager
    / %th Zv
    / %th Vz
    / %th Tst
    / %th Dg
    / %th Vd
    %th Out
    / %th Icon2
    %th Vin
    %th Cost
    %th Status
    / %th Commercial
    %th Tmp
    
    %th Phone11
    / %th Phone22
    / %th Phone33
    / %th Phone44
    %th Email
    %th
      Pas1
      %br/
      Pas2
      %br/
      Pas3
    %th Clientbirthday
    %th Prepay
    %th Date contract
    %th 
      Carpets
      Mudguard
      Tech 1
      Tech 2
      Tires
    %th Pas4
    %th Client adress
    %th Cause
    / %th Trade in price
    / %th Trade in desc
    / %th Used vin
    
    
  - @clients.each do |client|
    - client.cause = 1
    %tr{:class => ('info' if client.valid?)}
      %td
        = link_to 'Show', client
        = link_to 'Edit', edit_client_path(client)
        = link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }
        = link_to 'Договор', makedoc_path(:client_id => client.id, :doc_type => 1)
        = link_to 'Акт', makedoc_path(:client_id => client.id, :doc_type => 2)
        

      %td= client.fio
      %td= client.comment
      %td= client.phone1
      / %td= client.phone2
      / %td= client.phone3
      / %td= client.phone4
      %td= client.date
      %td= client.adress
      
      %td= client.brand
      %td= client.manager
      %td= client.car.model.name if client.car
      / %td= client.icon
      / %td= client.creditmanager
      / %td= client.zv
      / %td= client.vz
      / %td= client.tst
      / %td= client.dg
      / %td= client.vd
      %td= client.out
      / %td= client.icon2
      %td= client.vin
      %td= client.cost
      %td= client.status
      / %td= client.commercial
      %td= client.tmp
    
      %td= client.phone11
      / %td= client.phone22
      / %td= client.phone33
      / %td= client.phone44
      %td= client.email
      %td
        = client.pas1
        = client.pas2
        = client.pas3
      %td= client.clientbirthday
      %td= client.prepay
      %td= client.date_contract
      %td
        = client.carpets
        = client.mudguard
        = client.tech_1
        = client.tech_2
        = client.tires
      %td= client.pas4
      %td= client.client_adress
      %td= client.cause
      / %td= client.trade_in_price
      / %td= client.trade_in_desc
      / %td= client.used_vin

%br/
= will_paginate @posts
= link_to 'New Client', new_client_path

app/views/clients/new.html.haml
%h1 New client
= render 'form'
= link_to 'Back', clients_path

app/views/clients/show.html.haml
%p#notice= notice
%p
  %b Fio:
  = @client.fio
%p
  %b Comment:
  = @client.comment
%p
  %b Phone1:
  = @client.phone1
%p
  %b Phone2:
  = @client.phone2
%p
  %b Phone3:
  = @client.phone3
%p
  %b Phone4:
  = @client.phone4
%p
  %b Date:
  = @client.date
%p
  %b Adress:
  = @client.adress
%p
  %b Birthday:
  = @client.birthday
%p
  %b Brand:
  = @client.brand
%p
  %b Manager:
  = @client.manager
%p
  %b Model:
  = @client.model
%p
  %b Icon:
  = @client.icon
%p
  %b Creditmanager:
  = @client.creditmanager
%p
  %b Zv:
  = @client.zv
%p
  %b Vz:
  = @client.vz
%p
  %b Tst:
  = @client.tst
%p
  %b Dg:
  = @client.dg
%p
  %b Vd:
  = @client.vd
%p
  %b Out:
  = @client.out
%p
  %b Icon2:
  = @client.icon2
%p
  %b Vin:
  = @client.vin
%p
  %b Cost:
  = @client.cost
%p
  %b Status:
  = @client.status
%p
  %b Commercial:
  = @client.commercial
%p
  %b Tmp:
  = @client.tmp
%p
  %b Files:
  = @client.files
%p
  %b Phone11:
  = @client.phone11
%p
  %b Phone22:
  = @client.phone22
%p
  %b Phone33:
  = @client.phone33
%p
  %b Phone44:
  = @client.phone44
%p
  %b Email:
  = @client.email
%p
  %b Pas1:
  = @client.pas1
%p
  %b Pas2:
  = @client.pas2
%p
  %b Pas3:
  = @client.pas3
%p
  %b Clientbirthday:
  = @client.clientbirthday
%p
  %b Prepay:
  = @client.prepay
%p
  %b Date contract:
  = @client.date_contract
%p
  %b Carpets:
  = @client.carpets
%p
  %b Mudguard:
  = @client.mudguard
%p
  %b Tech 1:
  = @client.tech_1
%p
  %b Tech 2:
  = @client.tech_2
%p
  %b Tires:
  = @client.tires
%p
  %b Pas4:
  = @client.pas4
%p
  %b Client adress:
  = @client.client_adress
%p
  %b Cause:
  = @client.cause
%p
  %b Trade in price:
  = @client.trade_in_price
%p
  %b Trade in desc:
  = @client.trade_in_desc
%p
  %b Used vin:
  = @client.used_vin
= link_to 'Edit', edit_client_path(@client)
|
\#{link_to 'Back', clients_path}