config/routes.rb
DmsExt::Application.routes.draw do

  resources :opts

  match 'manage' => 'manage#index'
  
  resources :clients
  resources :interiors
  resources :colors

  devise_for :users

  resource :trade_ins

  resources :calendar do
    member do
      get 'day'
    end
  end

  resources :upload do
    member do
      get 'state'
      post 'state'
    end
  end

  resources :people do
    resources :communications
  end

  resources :cars do
    resource :contract
    resource :act
    resource :dkp
    resource :ckp
    resource :proposal
  end

  resources :models
  resources :managers

  resources :communications do
    member do
      get 'short'
    end
  end

  resources :contracts, :belongs_to => :car
  resources :proposals
  resources :checkins
  resources :acts
  resources :dkps

  root :to => 'cars#index'

  match 'cars/:id/info' => 'cars#info'
  match 'makedoc' => 'contracts#index'

end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :code, :color, :desc, :metallic
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  # GET /colors
  # GET /colors.json
  layout 'manage'
  def index
    @colors = Color.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colors }
    end
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
    @color = Color.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/new
  # GET /colors/new.json
  def new
    @color = Color.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(params[:color])

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render json: @color, status: :created, location: @color }
      else
        format.html { render action: "new" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colors/1
  # PUT /colors/1.json
  def update
    @color = Color.find(params[:id])

    respond_to do |format|
      if @color.update_attributes(params[:color])
        format.html { redirect_to colors_path, notice: 'Color was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color = Color.find(params[:id])
    @color.destroy

    respond_to do |format|
      format.html { redirect_to colors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.haml
= form_for(@color, :html => {:class => 'form form-horizontal'}) do |f|
  - if @color.errors.any?
    #error_explanation
      %h2
        = pluralize(@color.errors.count, "error")
        prohibited this color from being saved:
      %ul
        - @color.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :code, :class => 'control-label'
    .controls  
      = f.text_field :code
  .control-group
    = f.label :desc, :class => 'control-label'
    .controls  
      = f.text_field :desc
  .control-group
    = f.label :color, :class => 'control-label'
    .controls  
      = f.text_field :color
  .control-group
    = f.label :metallic, :class => 'control-label'
    .controls  
      = f.check_box :metallic
  .control-group
    .controls
      = f.submit

app/views/colors/edit.html.haml
%h1 Editing color
= render 'form'
= link_to 'Show', @color
|
\#{link_to 'Back', colors_path}

app/views/colors/index.html.haml
%h1 Цветы
= link_to 'New Color', new_color_path, :class => 'btn'
%table.table.table-condensed
  %tr
    %th Code
    %th Desc
    %th Color
    %th Metallic
    %th
    %th
    %th
  - @colors.each do |color|
    %tr
      %td= color.code
      %td= color.desc
      %td= color.color
      %td= color.metallic? ? 'v' : nil
      %td
        = link_to 'Show', color, :class => 'btn'
        = link_to 'Edit', edit_color_path(color), :class => 'btn'
        = link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'
%br/
= link_to 'New Color', new_color_path, :class => 'btn'

app/views/colors/new.html.haml
%h1 New color
= render 'form'
= link_to 'Back', colors_path

app/views/colors/show.html.haml
%p#notice= notice
%p
  %b Code:
  = @color.code
%p
  %b Desc:
  = @color.desc
%p
  %b Color:
  = @color.color
= link_to 'Edit', edit_color_path(@color)
|
\#{link_to 'Back', colors_path}